import { Dimensions } from 'react-native';
const { width: SCREEN_WIDTH } = Dimensions.get('window');

const SERVER_API_URL = 'https://api.sprinsoft.com/orderly/api';
const DEV_API_URL = 'http://192.168.100.8:3002/api';
const PROD_API_URL = 'https://orderly-api.vercel.app/api';
const colors = {
    light: {
        primary: 'hsl(335, 77%, 56%)',
        primaryLight: 'hsl(335,77%,85%)',
        primaryForeground: 'hsl(0, 0%, 100%)',
        secondary: 'hsl(262, 52%, 47%)',
        secondaryLight: 'hsl(262, 52%, 90%)',
        secondaryForeground: 'hsl(0, 0%, 96%)',
        accent: 'hsl(31, 89%, 63%)',
        accentLight: 'hsl(31, 89%, 85%)',
        background: 'hsl(0, 0%, 100%)',
        foreground: 'hsl(262, 47%, 13%)',
        muted: 'hsl(335, 20%, 95%)',
        mutedForeground: 'hsl(262, 20%, 40%)',
        border: 'hsl(335, 30%, 90%)',
        input: 'hsl(335, 30%, 95%)',
        ring: 'hsl(335, 77%, 76%)',
        error: 'hsl(0, 100%, 40%)',
    },
    dark: {
        primary: 'hsl(346.8, 77.2%, 49.8%)',
        primaryLight: 'hsl(346.8, 77.2%, 60.8%)',
        primaryForeground: 'hsl(355.7, 100%, 97.3%)',
        secondary: 'hsl(240, 3.7%, 15.9%)',
        secondaryLight: 'hsl(240, 52%, 65%)',
        secondaryForeground: 'hsl(0, 0%, 96%)',
        accent: 'hsl(12, 6.5%, 15.1%)',
        accentLight: 'hsl(31, 89%, 40%)',
        background: 'hsl(20, 14.3%, 4.1%)',
        foreground: 'hsl(0, 0%, 95%)',
        muted: 'hsl(0, 0%, 15%)',
        mutedForeground: 'hsl(240, 5%, 64.9%)',
        border: 'hsl(240, 3.7%, 15.9%)',
        input: 'hsl(240, 3.7%, 15.9%)',
        ring: 'hsl(346.8, 77.2%, 49.8%)',
        error: 'hsl(0, 100%, 40%)',
    }
};

const fontSizes = {
    xs: SCREEN_WIDTH * 0.027,
    sm: SCREEN_WIDTH * 0.031,
    base: SCREEN_WIDTH * 0.035,
    lg: SCREEN_WIDTH * 0.039,
    xl: SCREEN_WIDTH * 0.043,
    '2xl': SCREEN_WIDTH * 0.051,
    '3xl': SCREEN_WIDTH * 0.063,
    '4xl': SCREEN_WIDTH * 0.075,
    '5xl': SCREEN_WIDTH * 0.099,
};

const fonts = {
    normal: 'Geist-Regular',
    medium: 'Geist-Medium',
    semibold: 'Geist-SemiBold',
    bold: 'Geist-Bold',
    extrabold: 'Geist-ExtraBold'
};

const lineHeights = {
    tight: 1.25,
    normal: 1.5,
    relaxed: 1.75,
};

const borderRadius = {
    none: 0,
    sm: 2,
    default: 4,
    md: 6,
    lg: 8,
    xl: 12,
    '2xl': 16,
    '3xl': 24,
    full: 9999,
};

const healthTips = [
    "Track your period regularly to understand your cycle",
    "Use a heating pad or hot water bottle for cramps",
    "Drink plenty of water during your period",
    "Take light walks to help with period pain",
    "Get enough sleep every night",
    "Eat foods with iron like meat and leafy greens",
    "Change your pads or tampons often",
    "Wear comfy underwear during your period",
    "Try deep breathing when you feel stressed",
    "Eat lots of fruits and vegetables",
    "Take pain medicine if cramps are bad",
    "Cut down on coffee if it makes you feel worse",
    "Do gentle stretches to feel better",
    "Write down your symptoms each month",
    "Eat small meals to feel less bloated",
    "Stay active but don't push too hard",
    "Use unscented pads to avoid itching",
    "Try warm tea for period pain",
    "Keep extra pads in your bag",
    "Eat less salt to reduce bloating",
    "Use a period tracking app",
    "Stay warm with cozy clothes",
    "Take time to rest when needed",
    "Talk to a doctor if your period is very heavy",
    "Do things you enjoy during your period",
    "Wear loose, comfy clothes during your period",
    "Put a dark towel on your bed at night",
    "Keep wet wipes in your period kit",
    "Try warm showers for pain relief",
    "Pack spare underwear when going out",
    "Eat bananas to help with cramps",
    "Keep track of which pads work best for you",
    "Set reminders to change your pad",
    "Try sleeping on your side with a pillow between legs",
    "Keep hair ties handy for warm days",
    "Have a regular bedtime during your period",
    "Pack dark colored pants for work or school",
    "Keep pain pills in your period kit",
    "Try holding an ice pack on your lower back",
    "Use period panty liners on light days",
    "Keep crackers nearby for upset stomach",
    "Try warm milk before bed",
    "Use baby wipes for quick clean ups",
    "Keep a spare sweater at work",
    "Try rubbing your feet to feel better",
    "Eat plain foods if feeling sick",
    "Keep hand sanitizer in your period kit",
    "Try hugging a warm stuffed animal",
    "Use toilet seat covers in public bathrooms",
    "Keep your belly warm",
    "Bring mints for nausea",
    "Try sitting with good posture",
    "Keep spare socks in your bag",
    "Use paper bags to wrap used pads",
    "Try warm face washing before bed",
    "Keep tissue paper handy",
    "Try holding your hands under warm water",
    "Use a small pillow for back support",
    "Keep hair bands in your period kit",
    "Try wearing slip-on shoes",
    "Keep backup pads at work or school",
    "Use body powder to feel fresh",
    "Try warm neck stretches",
    "Keep extra hair clips ready",
    "Use roll-on pain relief",
    "Try wearing dark pajamas",
    "Keep wet towels nearby",
    "Use stick-on heat patches",
    "Try warm foot soaks",
    "Keep breath mints handy",
    "Use paper bags for pad disposal",
    "Try gentle arm stretches",
    "Keep face wipes in your bag",
    "Use hand cream after washing",
    "Try humming to distract from cramps"
];

export {
    colors,
    fontSizes,
    fonts,
    lineHeights,
    borderRadius,
    DEV_API_URL,
    PROD_API_URL,
    healthTips,
    SERVER_API_URL
};
